### PR TITLE
Popup window

### PR DESCRIPTION
**Pull request by Ngufor-emmanuella**
In this project a hambuger button is built so that that the user clicks on the menu bar or hamburger button displays the different menu options that is portfolio , about and contact and when the user clicks on each of the nav links it takes them to the page in the website
## Built With

- HTML
- CSS
-javascript
- Linters

### CODE REVIEW

**Comment by BenMukebo** [comment]
Hey @Ngufor-emmanuella, @Jhaman1895 !!
This is a Portfolio: mobile menu or Portfolio: details popup window ?

**Comment by Jhaman1895** [comment]
> Hey @Ngufor-emmanuella, @Jhaman1895 !! This is a Portfolio: mobile menu or Portfolio: details popup window ?

Hi, it is the mobile menu.

**Comment by Ngufor-emmanuella** [comment]
hello this is a portfolio mobile menu

**Comment by Ngufor-emmanuella** [comment]
hello @Jhaman1895 this a portfolio mobile menu

**Comment by BenMukebo** [comment]
Alright let me invalidate that, the fact is this project has been claimed twice but since I'm the one with the wrong milestone I'm going to invalidate it on my dashboard

Have you submitted the Portfolio: details popup window yet?

**Review by BenMukebo — CHANGES_REQUESTED** [review]
## Status: Invalid ❌

### Hi @Ngufor-emmanuella, @Jhaman1895,
Please fix the issue mentioned below and then request for code review

### Reason

- [ ] I think you have submitted the wrong project. From your PR it looks like you are about to request for "Portfolio: mobile menu" instead of "Portfolio: details popup window ".

#### Please make sure to submit code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# INVALID ❌ ❌ ❌ 

Hi @Ngufor-emmanuella, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - As the previous code reviewer mentioned, if this is a Pull Request for the mobile menu implementation, you should submit this project for the "Portfolio: mobile menu" instead of "Portfolio: details popup window ". Also, your branch name mentions the popup-window feature, I would suggest you change the branch name to something like 'mobile-menu' so it can make more sense and submit this project again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

**Comment by Ngufor-emmanuella** [comment]
ok thanks

**Pull request merged**
